# docker-compose.yml - Mac optimized
version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:cached # cached flag improves performance on Mac
    environment:
      - PYTHONPATH=/app
    platform: linux/amd64 # Ensures compatibility with Azure
