name: Build and Deploy to Azure App Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: rag-app-production-clvd
  CONTAINER_REGISTRY: ragmvpregistryclvd.azurecr.io
  IMAGE_NAME: rag-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.optimized
          platforms: linux/amd64
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to AKS Learning Cluster
        run: |
          az aks get-credentials --resource-group rg-rag-mvp-free-2 --name aks-rag-learning

          # Update deployment with real environment variables
          kubectl set env deployment/rag-app \
            AZURE_OPENAI_ENDPOINT="${{ secrets.AZURE_OPENAI_ENDPOINT }}" \
            AZURE_OPENAI_KEY="${{ secrets.AZURE_OPENAI_KEY }}" \
            AZURE_SEARCH_ENDPOINT="${{ secrets.AZURE_SEARCH_ENDPOINT }}" \
            AZURE_SEARCH_KEY="${{ secrets.AZURE_SEARCH_KEY }}" \
            OPENAI_API_VERSION="2024-02-15-preview" \
            AZURE_OPENAI_DEPLOYMENT_NAME="gpt-35-turbo-0125" \
            AZURE_OPENAI_EMBEDDING_DEPLOYMENT_NAME="text-embedding-ada-002"

          kubectl set image deployment/rag-app rag-app=${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          kubectl rollout status deployment/rag-app --timeout=300s
        if: github.ref == 'refs/heads/main'
